mode = "light"

accent = "#a7593d"
selection = "#ebcec0"
muted = "#897669"

background = "#feefe5"
dark_background = "#f6e5d9"
darker_background = "#ead7ca"
lighter_background = "#f0dcce"

foreground = "#3b2a1d"
dark_foreground = "#715f53"
light_foreground = "#5a493d"
bright_foreground = "#201309"

hyprland_active_border = "rgba(a7593dee) rgba(498143ee) 45deg"
hyprland_inactive_border = "rgba(897669aa)"

red = "#ab422c"
yellow = "#8a690a"
orange = "#9f5700"
green = "#497b2b"
cyan = "#127a77"
blue = "#006b9b"
magenta = "#9d4578"
brown = "#774826"

bright_red = "#992d15"
bright_yellow = "#745700"
bright_green = "#33670b"
bright_cyan = "#0d6563"
bright_blue = "#065981"
bright_magenta = "#8b3167"
