mode = "light"

accent = "#597808"
selection = "#ccdab6"
muted = "#737f6b"

background = "#edf6e7"
dark_background = "#e2edda"
darker_background = "#d4e0cc"
lighter_background = "#d9e5d0"

foreground = "#27321f"
dark_foreground = "#5d6755"
light_foreground = "#47513f"
bright_foreground = "#11190b"

hyprland_active_border = "rgba(597808ee) rgba(84702eee) 45deg"
hyprland_inactive_border = "rgba(737f6baa)"

red = "#98392d"
yellow = "#78710d"
orange = "#8e5704"
green = "#4e7902"
cyan = "#4b7955"
blue = "#7a5e2d"
magenta = "#915157"
brown = "#774826"

bright_red = "#862419"
bright_yellow = "#655e00"
bright_green = "#416600"
bright_cyan = "#376642"
bright_blue = "#694d17"
bright_magenta = "#803f45"
