mode = "light"

accent = "#b14f41"
selection = "#eccdc2"
muted = "#8b7768"

background = "#fdf0e6"
dark_background = "#f8e5d6"
darker_background = "#ecd7c8"
lighter_background = "#f2dccb"

foreground = "#3c291a"
dark_foreground = "#715f52"
light_foreground = "#5b493b"
bright_foreground = "#201308"

hyprland_active_border = "rgba(b14f41ee) rgba(886e2eee) 45deg"
hyprland_inactive_border = "rgba(8b7768aa)"

red = "#ac4134"
yellow = "#8d680c"
orange = "#a1550b"
green = "#587819"
cyan = "#017c78"
blue = "#0069a2"
magenta = "#9b457d"
brown = "#774826"

bright_red = "#9a2c20"
bright_yellow = "#775600"
bright_green = "#476501"
bright_cyan = "#006764"
bright_blue = "#025788"
bright_magenta = "#89326c"
