mode = "light"

accent = "#7b702d"
selection = "#d1d9c7"
muted = "#6c7f7b"

background = "#e9f6f3"
dark_background = "#ddece9"
darker_background = "#cfe0dc"
lighter_background = "#d3e5e1"

foreground = "#1f322e"
dark_foreground = "#556864"
light_foreground = "#3f524d"
bright_foreground = "#0a1916"

hyprland_active_border = "rgba(7b702dee) rgba(278271ee) 45deg"
hyprland_inactive_border = "rgba(6c7f7baa)"

red = "#98403c"
yellow = "#816e20"
orange = "#945619"
green = "#3e7c4d"
cyan = "#066961"
blue = "#187289"
magenta = "#875d82"
brown = "#774826"

bright_red = "#862c2b"
bright_yellow = "#6c5a03"
bright_green = "#266839"
bright_cyan = "#07564f"
bright_blue = "#0a6075"
bright_magenta = "#754c71"
