mode = "light"

accent = "#9a6207"
selection = "#dfd2c7"
muted = "#7a778c"

background = "#f2f1fd"
dark_background = "#e8e6f9"
darker_background = "#dbd9ed"
lighter_background = "#e0ddf3"

foreground = "#2e2b3e"
dark_foreground = "#636073"
light_foreground = "#4d4a5d"
bright_foreground = "#161422"

hyprland_active_border = "rgba(9a6207ee) rgba(b14f41ee) 45deg"
hyprland_inactive_border = "rgba(7a778caa)"

red = "#9c200b"
yellow = "#916600"
orange = "#954c00"
green = "#4a792c"
cyan = "#3d7a61"
blue = "#8b4d05"
magenta = "#9a4254"
brown = "#774826"

bright_red = "#831301"
bright_yellow = "#795500"
bright_green = "#376612"
bright_cyan = "#24664d"
bright_blue = "#743f05"
bright_magenta = "#882e43"
