mode = "dark"

accent = "#fd8a8f"
selection = "#532d2b"
muted = "#7f6e5f"

background = "#110904"
dark_background = "#0d0703"
darker_background = "#090502"
lighter_background = "#21170e"

foreground = "#ecdfd4"
dark_foreground = "#998e85"
light_foreground = "#d6c8bc"
bright_foreground = "#fcf5f0"

hyprland_active_border = "rgba(fd8a8fee) rgba(bca169ee) 45deg"
hyprland_inactive_border = "rgba(7f6e5faa)"

red = "#df6768"
yellow = "#f5cb70"
orange = "#f39759"
green = "#acc188"
cyan = "#f2daba"
blue = "#d7907e"
magenta = "#eb99ac"
brown = "#865634"

bright_red = "#eb8784"
bright_yellow = "#ffe5b0"
bright_green = "#c4d6a7"
bright_cyan = "#fdecd4"
bright_blue = "#e6aa9b"
bright_magenta = "#fab5c3"
