mode = "dark"

accent = "#fe8a88"
selection = "#4f2f28"
muted = "#72745d"

background = "#0b0c02"
dark_background = "#080902"
darker_background = "#060601"
lighter_background = "#1a1b0c"

foreground = "#e1e3d2"
dark_foreground = "#909183"
light_foreground = "#caccbb"
bright_foreground = "#f7f8f0"

hyprland_active_border = "rgba(fe8a88ee) rgba(c79e41ee) 45deg"
hyprland_inactive_border = "rgba(72745daa)"

red = "#e45c5e"
yellow = "#ffd16b"
orange = "#fb954d"
green = "#8fc990"
cyan = "#a5ded6"
blue = "#b1a1d1"
magenta = "#ef86a0"
brown = "#865634"

bright_red = "#f1807e"
bright_yellow = "#ffedc8"
bright_green = "#adddad"
bright_cyan = "#c4f3ec"
bright_blue = "#c6b9e1"
bright_magenta = "#fca4b8"
