mode = "dark"

accent = "#e7ddc8"
selection = "#514e45"
muted = "#777367"

background = "#171612"
dark_background = "#11110e"
darker_background = "#0c0b09"
lighter_background = "#272520"

foreground = "#e4e1d8"
dark_foreground = "#96948d"
light_foreground = "#cecac0"
bright_foreground = "#f9f7ef"

hyprland_active_border = "rgba(e7ddc8ee) rgba(c69b78ee) 45deg"
hyprland_inactive_border = "rgba(777367aa)"

red = "#cc9490"
yellow = "#e4c195"
orange = "#dba98f"
green = "#a6b990"
cyan = "#8ac4c3"
blue = "#8ab0ce"
magenta = "#d3a4be"
brown = "#885836"

bright_red = "#dcada9"
bright_yellow = "#f6d9b5"
bright_green = "#beceac"
bright_cyan = "#a9d8d8"
bright_blue = "#a6c5df"
bright_magenta = "#e4bdd3"
