mode = "dark"

accent = "#e69e79"
selection = "#4e3627"
muted = "#7c6f61"

background = "#130d07"
dark_background = "#0e0a05"
darker_background = "#0a0704"
lighter_background = "#221c14"

foreground = "#e9e0d5"
dark_foreground = "#989087"
light_foreground = "#d3c9bd"
bright_foreground = "#fbf6f0"

hyprland_active_border = "rgba(e69e79ee) rgba(dc8c85ee) 45deg"
hyprland_inactive_border = "rgba(7c6f61aa)"

red = "#e48877"
yellow = "#ebc16a"
orange = "#eea368"
green = "#a0bd77"
cyan = "#64cbc5"
blue = "#6db4e1"
magenta = "#e28ea9"
brown = "#865634"

bright_red = "#f1a495"
bright_yellow = "#fcd994"
bright_green = "#b9d298"
bright_cyan = "#8edfd9"
bright_blue = "#90c9ef"
bright_magenta = "#f1aac0"
