mode = "light"

accent = "#806c00"
selection = "#dcd5b3"
muted = "#807a68"

background = "#f6f2e5"
dark_background = "#ede9d9"
darker_background = "#e0dbca"
lighter_background = "#e6e0ce"

foreground = "#332e1c"
dark_foreground = "#686351"
light_foreground = "#524d3c"
bright_foreground = "#1a1608"

hyprland_active_border = "rgba(806c00ee) rgba(8f5e8aee) 45deg"
hyprland_inactive_border = "rgba(807a68aa)"

red = "#a54743"
yellow = "#826b00"
orange = "#9b5811"
green = "#52792f"
cyan = "#007a7a"
blue = "#16699c"
magenta = "#8f4d88"
brown = "#774826"

bright_red = "#933331"
bright_yellow = "#6d5a06"
bright_green = "#3f6615"
bright_cyan = "#006565"
bright_blue = "#005886"
bright_magenta = "#7d3b77"
