mode = "light"

accent = "#8e671f"
selection = "#e1d3b9"
muted = "#837968"

background = "#f9f1e5"
dark_background = "#f0e7d9"
darker_background = "#e4daca"
lighter_background = "#e9dfce"

foreground = "#362c1c"
dark_foreground = "#6c6251"
light_foreground = "#554c3c"
bright_foreground = "#1c1508"

hyprland_active_border = "rgba(8e671fee) rgba(617d22ee) 45deg"
hyprland_inactive_border = "rgba(837968aa)"

red = "#a5483e"
yellow = "#8f6604"
orange = "#9f561c"
green = "#577823"
cyan = "#007a79"
blue = "#15699c"
magenta = "#954b7d"
brown = "#774826"

bright_red = "#93342c"
bright_yellow = "#775508"
bright_green = "#446500"
bright_cyan = "#006564"
bright_blue = "#005786"
bright_magenta = "#83386d"
