mode = "dark"

accent = "#dca285"
selection = "#483229"
muted = "#7e6d66"

background = "#0e0705"
dark_background = "#0b0504"
darker_background = "#070403"
lighter_background = "#1d1511"

foreground = "#ebded8"
dark_foreground = "#978c88"
light_foreground = "#d6c7c1"
bright_foreground = "#fdf5f1"

hyprland_active_border = "rgba(dca285ee) rgba(77b0b3ee) 45deg"
hyprland_inactive_border = "rgba(7e6d66aa)"

red = "#dc8d7c"
yellow = "#e5c379"
orange = "#e6a673"
green = "#a2bc7f"
cyan = "#71c9c9"
blue = "#7ab2dc"
magenta = "#d494bb"
brown = "#865634"

bright_red = "#eaa899"
bright_yellow = "#f7db9f"
bright_green = "#bbd19e"
bright_cyan = "#97dddd"
bright_blue = "#9ac7eb"
bright_magenta = "#e4aecf"
