mode = "light"

accent = "#a85556"
selection = "#eccdc6"
muted = "#8a766a"

background = "#ffefe6"
dark_background = "#f7e4da"
darker_background = "#ebd7cb"
lighter_background = "#f1dbcf"

foreground = "#3c291e"
dark_foreground = "#725f54"
light_foreground = "#5b493e"
bright_foreground = "#20120a"

hyprland_active_border = "rgba(a85556ee) rgba(916932ee) 45deg"
hyprland_inactive_border = "rgba(8a766aaa)"

red = "#923235"
yellow = "#966417"
orange = "#984a1e"
green = "#616d3a"
cyan = "#826956"
blue = "#84513e"
magenta = "#8f4a61"
brown = "#774826"

bright_red = "#801c24"
bright_yellow = "#7f5100"
bright_green = "#505c26"
bright_cyan = "#6f5643"
bright_blue = "#733f2d"
bright_magenta = "#7e3850"
