mode = "dark"

accent = "#dba475"
selection = "#4c3624"
muted = "#806e61"

background = "#140b05"
dark_background = "#0f0804"
darker_background = "#0a0603"
lighter_background = "#241911"

foreground = "#ecded5"
dark_foreground = "#9a8e86"
light_foreground = "#d6c7bd"
bright_foreground = "#fcf5f0"

hyprland_active_border = "rgba(dba475ee) rgba(ee8266ee) 45deg"
hyprland_inactive_border = "rgba(806e61aa)"

red = "#ef806f"
yellow = "#f9b971"
orange = "#f79c69"
green = "#9fbd76"
cyan = "#61ccc7"
blue = "#71b2e4"
magenta = "#d990bf"
brown = "#865634"

bright_red = "#fb9e8f"
bright_yellow = "#fed6ad"
bright_green = "#b8d297"
bright_cyan = "#8ddfdb"
bright_blue = "#93c7f1"
bright_magenta = "#e9abd2"
