mode = "dark"

accent = "#ee90b1"
selection = "#55303d"
muted = "#846973"

background = "#190a10"
dark_background = "#13080c"
darker_background = "#0d0508"
lighter_background = "#29181f"

foreground = "#f0dbe2"
dark_foreground = "#9e8c92"
light_foreground = "#dac4cb"
bright_foreground = "#fdf4f7"

hyprland_active_border = "rgba(ee90b1ee) rgba(89b18aee) 45deg"
hyprland_inactive_border = "rgba(846973aa)"

red = "#e57693"
yellow = "#f3d392"
orange = "#f8a27c"
green = "#98c598"
cyan = "#aedcd2"
blue = "#cc96c6"
magenta = "#f893bc"
brown = "#865634"

bright_red = "#f294aa"
bright_yellow = "#ffecc6"
bright_green = "#b4d9b4"
bright_cyan = "#cbf1e8"
bright_blue = "#ddb0d8"
bright_magenta = "#ffb5d1"
