mode = "dark"

accent = "#b5a4ea"
selection = "#3e3851"
muted = "#736e80"

background = "#100e16"
dark_background = "#0c0b11"
darker_background = "#08070b"
lighter_background = "#1f1c26"

foreground = "#e2dfec"
dark_foreground = "#92909b"
light_foreground = "#ccc8d7"
bright_foreground = "#f7f5fd"

hyprland_active_border = "rgba(b5a4eaee) rgba(e7d6b3ee) 45deg"
hyprland_inactive_border = "rgba(736e80aa)"

red = "#df879b"
yellow = "#f4dca1"
orange = "#f5af8c"
green = "#9cc49c"
cyan = "#a8d1ee"
blue = "#aaa0e6"
magenta = "#d7adf7"
brown = "#865634"

bright_red = "#eda3b3"
bright_yellow = "#feedc5"
bright_green = "#b7d8b7"
bright_cyan = "#c8e6fd"
bright_blue = "#c0b9f3"
bright_magenta = "#e7cafd"
