mode = "dark"

accent = "#ecdcc1"
selection = "#47423c"
muted = "#737079"

background = "#070608"
dark_background = "#050506"
darker_background = "#040304"
lighter_background = "#141316"

foreground = "#e2e0e8"
dark_foreground = "#8f8d93"
light_foreground = "#ccc9d2"
bright_foreground = "#f8f5fd"

hyprland_active_border = "rgba(ecdcc1ee) rgba(d78e8dee) 45deg"
hyprland_inactive_border = "rgba(737079aa)"

red = "#d78e8f"
yellow = "#dec588"
orange = "#e2a782"
green = "#9cbd8b"
cyan = "#7ac7c7"
blue = "#80b1d8"
magenta = "#d9a0c3"
brown = "#865634"

bright_red = "#e6a8a8"
bright_yellow = "#f1dcaa"
bright_green = "#b6d2a8"
bright_cyan = "#9ddbdb"
bright_blue = "#9ec6e7"
bright_magenta = "#eabad7"
