mode = "light"

accent = "#8e6707"
selection = "#e5d1b7"
muted = "#89766b"

background = "#fdefe8"
dark_background = "#f5e5dc"
darker_background = "#e9d7ce"
lighter_background = "#efdcd1"

foreground = "#3a2920"
dark_foreground = "#715f55"
light_foreground = "#5a493f"
bright_foreground = "#1f130b"

hyprland_active_border = "rgba(8e6707ee) rgba(a55a37ee) 45deg"
hyprland_inactive_border = "rgba(89766baa)"

red = "#ac4132"
yellow = "#8d6800"
orange = "#a15502"
green = "#58781a"
cyan = "#137a76"
blue = "#0b6a9c"
magenta = "#9c457a"
brown = "#774826"

bright_red = "#992c1e"
bright_yellow = "#745500"
bright_green = "#456300"
bright_cyan = "#0d6562"
bright_blue = "#015884"
bright_magenta = "#8a3169"
