mode = "dark"

accent = "#e89b80"
selection = "#4f3028"
muted = "#846b66"

background = "#140706"
dark_background = "#0f0505"
darker_background = "#0a0403"
lighter_background = "#241512"

foreground = "#f0dcd9"
dark_foreground = "#9c8b89"
light_foreground = "#dac5c1"
bright_foreground = "#fdf4f3"

hyprland_active_border = "rgba(e89b80ee) rgba(80b57aee) 45deg"
hyprland_inactive_border = "rgba(846b66aa)"

red = "#eb846c"
yellow = "#edc158"
orange = "#f3a058"
green = "#90c277"
cyan = "#4dcec9"
blue = "#60b5e9"
magenta = "#e28aba"
brown = "#865634"

bright_red = "#f8a18d"
bright_yellow = "#fdda88"
bright_green = "#acd698"
bright_cyan = "#81e1dd"
bright_blue = "#87caf6"
bright_magenta = "#f1a6ce"
