mode = "dark"

accent = "#d1ac4e"
selection = "#453918"
muted = "#76725d"

background = "#0e0c03"
dark_background = "#0b0902"
darker_background = "#070602"
lighter_background = "#1d1b0d"

foreground = "#e4e2d2"
dark_foreground = "#939183"
light_foreground = "#cecbba"
bright_foreground = "#f8f7f0"

hyprland_active_border = "rgba(d1ac4eee) rgba(da8f74ee) 45deg"
hyprland_inactive_border = "rgba(76725daa)"

red = "#eb836e"
yellow = "#e9c358"
orange = "#f2a157"
green = "#9ac06d"
cyan = "#49cec9"
blue = "#67b2ee"
magenta = "#e28abc"
brown = "#865634"

bright_red = "#f8a08d"
bright_yellow = "#fadb88"
bright_green = "#b4d491"
bright_cyan = "#7fe1dc"
bright_blue = "#8bc8f9"
bright_magenta = "#f1a7cf"
