mode = "light"

accent = "#c33a2b"
selection = "#e2ccc5"
muted = "#707e77"

background = "#ebf5f0"
dark_background = "#e0ece6"
darker_background = "#d2dfd9"
lighter_background = "#d7e4dd"

foreground = "#24312b"
dark_foreground = "#586760"
light_foreground = "#43514a"
bright_foreground = "#0e1914"

hyprland_active_border = "rgba(c33a2bee) rgba(a45e08ee) 45deg"
hyprland_inactive_border = "rgba(707e77aa)"

red = "#b8312b"
yellow = "#986404"
orange = "#aa4f04"
green = "#4a7c04"
cyan = "#0b7b7d"
blue = "#0768a4"
magenta = "#a13e7f"
brown = "#774826"

bright_red = "#a51114"
bright_yellow = "#7e5202"
bright_green = "#3d6706"
bright_cyan = "#006566"
bright_blue = "#05578a"
bright_magenta = "#8f286e"
