mode = "light"

accent = "#b64b38"
selection = "#ebccbe"
muted = "#847967"

background = "#faf1e4"
dark_background = "#f1e7d7"
darker_background = "#e4dac9"
lighter_background = "#eadfcc"

foreground = "#362c1b"
dark_foreground = "#6c6250"
light_foreground = "#564c3b"
bright_foreground = "#1c1507"

hyprland_active_border = "rgba(b64b38ee) rgba(867003ee) 45deg"
hyprland_inactive_border = "rgba(847967aa)"

red = "#ac4038"
yellow = "#876b09"
orange = "#a05601"
green = "#507a21"
cyan = "#087a78"
blue = "#0569a0"
magenta = "#9c457b"
brown = "#774826"

bright_red = "#992a25"
bright_yellow = "#705808"
bright_green = "#3c6502"
bright_cyan = "#036564"
bright_blue = "#065786"
bright_magenta = "#8a316a"
