mode = "light"

accent = "#a75463"
selection = "#eccdc9"
muted = "#8a756a"

background = "#ffefe6"
dark_background = "#f7e4da"
darker_background = "#ebd7cc"
lighter_background = "#f1dbd0"

foreground = "#3c291e"
dark_foreground = "#725f54"
light_foreground = "#5c483e"
bright_foreground = "#20120a"

hyprland_active_border = "rgba(a75463ee) rgba(916932ee) 45deg"
hyprland_inactive_border = "rgba(8a756aaa)"

red = "#a54649"
yellow = "#966500"
orange = "#a35425"
green = "#52792f"
cyan = "#13797a"
blue = "#0d6a9b"
magenta = "#984a77"
brown = "#774826"

bright_red = "#933238"
bright_yellow = "#7c5300"
bright_green = "#3f6615"
bright_cyan = "#0e6465"
bright_blue = "#045883"
bright_magenta = "#863766"
