mode = "dark"

accent = "#f2a89d"
selection = "#563935"
muted = "#846b66"

background = "#1a0e0c"
dark_background = "#140b09"
darker_background = "#0d0706"
lighter_background = "#2b1c19"

foreground = "#efdcd9"
dark_foreground = "#9e8e8b"
light_foreground = "#d9c5c2"
bright_foreground = "#fdf4f3"

hyprland_active_border = "rgba(f2a89dee) rgba(b4a46aee) 45deg"
hyprland_inactive_border = "rgba(846b66aa)"

red = "#e4877b"
yellow = "#e2c56a"
orange = "#eca366"
green = "#9bbf77"
cyan = "#5bcccd"
blue = "#6fb2e6"
magenta = "#db8fbd"
brown = "#865634"

bright_red = "#f1a398"
bright_yellow = "#f4dd94"
bright_green = "#b5d398"
bright_cyan = "#89dfe0"
bright_blue = "#91c7f3"
bright_magenta = "#ebaad0"
