mode = "dark"

accent = "#b5b761"
selection = "#40411f"
muted = "#72745d"

background = "#121306"
dark_background = "#0e0e05"
darker_background = "#090a03"
lighter_background = "#212213"

foreground = "#e1e3d2"
dark_foreground = "#929484"
light_foreground = "#caccbb"
bright_foreground = "#f7f8f0"

hyprland_active_border = "rgba(b5b761ee) rgba(bf9f6aee) 45deg"
hyprland_inactive_border = "rgba(72745daa)"

red = "#dc8b85"
yellow = "#e9c17a"
orange = "#e9a479"
green = "#aabb68"
cyan = "#6bc9cb"
blue = "#76b2de"
magenta = "#d593bb"
brown = "#865634"

bright_red = "#eaa6a0"
bright_yellow = "#fbd9a0"
bright_green = "#c1d08d"
bright_cyan = "#93ddde"
bright_blue = "#96c7ec"
bright_magenta = "#e5aecf"
