mode = "light"

accent = "#8c6a05"
selection = "#e0d4b4"
muted = "#827968"

background = "#f8f2e5"
dark_background = "#efe8d9"
darker_background = "#e2dbca"
lighter_background = "#e8dfce"

foreground = "#352d1c"
dark_foreground = "#6b6251"
light_foreground = "#544c3c"
bright_foreground = "#1b1508"

hyprland_active_border = "rgba(8c6a05ee) rgba(577e4aee) 45deg"
hyprland_inactive_border = "rgba(827968aa)"

red = "#a5483f"
yellow = "#8e6703"
orange = "#9e561b"
green = "#4d7a35"
cyan = "#0a7b7d"
blue = "#20689c"
magenta = "#954b7b"
brown = "#774826"

bright_red = "#93342d"
bright_yellow = "#765607"
bright_green = "#39671e"
bright_cyan = "#076668"
bright_blue = "#055789"
bright_magenta = "#84386a"
