mode = "light"

accent = "#856c0c"
selection = "#e0d4b6"
muted = "#847869"

background = "#faf1e6"
dark_background = "#f1e7da"
darker_background = "#e5d9cc"
lighter_background = "#eaded0"

foreground = "#372c1d"
dark_foreground = "#6d6153"
light_foreground = "#564b3d"
bright_foreground = "#1d1409"

hyprland_active_border = "rgba(856c0cee) rgba(9c6045ee) 45deg"
hyprland_inactive_border = "rgba(847869aa)"

red = "#a5483c"
yellow = "#886b02"
orange = "#9c5912"
green = "#55782f"
cyan = "#007c79"
blue = "#1e699b"
magenta = "#974a76"
brown = "#774826"

bright_red = "#933429"
bright_yellow = "#705805"
bright_green = "#426516"
bright_cyan = "#006765"
bright_blue = "#025888"
bright_magenta = "#853765"
