mode = "dark"

accent = "#f6946d"
selection = "#552e20"
muted = "#886a5e"

background = "#160602"
dark_background = "#110502"
darker_background = "#0b0301"
lighter_background = "#27140c"

foreground = "#f2dcd3"
dark_foreground = "#9e8b84"
light_foreground = "#dcc5bc"
bright_foreground = "#fdf5f2"

hyprland_active_border = "rgba(f6946dee) rgba(c59c6dee) 45deg"
hyprland_inactive_border = "rgba(886a5eaa)"

red = "#eb836f"
yellow = "#fdb85f"
orange = "#f89c63"
green = "#99c071"
cyan = "#50cec9"
blue = "#68b3eb"
magenta = "#e08bbe"
brown = "#865634"

bright_red = "#f8a08f"
bright_yellow = "#fdd7a9"
bright_green = "#b4d493"
bright_cyan = "#83e1dd"
bright_blue = "#8dc8f7"
bright_magenta = "#efa7d1"
