mode = "dark"

accent = "#c8b05a"
selection = "#4a3c1f"
muted = "#816d5f"

background = "#190f08"
dark_background = "#130b06"
darker_background = "#0d0804"
lighter_background = "#291e15"

foreground = "#edded4"
dark_foreground = "#9c8f86"
light_foreground = "#d7c7bc"
bright_foreground = "#fcf5f0"

hyprland_active_border = "rgba(c8b05aee) rgba(86b37dee) 45deg"
hyprland_inactive_border = "rgba(816d5faa)"

red = "#e48682"
yellow = "#e5c46a"
orange = "#eea26a"
green = "#90c181"
cyan = "#5eccca"
blue = "#71b2e5"
magenta = "#da8fbe"
brown = "#865634"

bright_red = "#f1a29e"
bright_yellow = "#f7dc94"
bright_green = "#acd5a0"
bright_cyan = "#8bdfde"
bright_blue = "#93c7f2"
bright_magenta = "#e9aad1"
