mode = "dark"

accent = "#e49f75"
selection = "#4d3324"
muted = "#806d61"

background = "#120904"
dark_background = "#0e0703"
darker_background = "#090502"
lighter_background = "#22170f"

foreground = "#edded5"
dark_foreground = "#9a8d86"
light_foreground = "#d7c7bd"
bright_foreground = "#fcf5f1"

hyprland_active_border = "rgba(e49f75ee) rgba(e6857eee) 45deg"
hyprland_inactive_border = "rgba(806d61aa)"

red = "#d97464"
yellow = "#f9be78"
orange = "#ec9867"
green = "#afb784"
cyan = "#f8d7be"
blue = "#ce9677"
magenta = "#e89da2"
brown = "#865634"

bright_red = "#e69183"
bright_yellow = "#fedbb3"
bright_green = "#c6cca2"
bright_cyan = "#ffeada"
bright_blue = "#deaf95"
bright_magenta = "#f7b8bb"
