mode = "light"

accent = "#9a6041"
selection = "#e4d1c5"
muted = "#84786d"

background = "#f9f1ea"
dark_background = "#f0e7de"
darker_background = "#e3d9d0"
lighter_background = "#e9ded4"

foreground = "#372b21"
dark_foreground = "#6d6156"
light_foreground = "#564b40"
bright_foreground = "#1d140c"

hyprland_active_border = "rgba(9a6041ee) rgba(3d7d81ee) 45deg"
hyprland_inactive_border = "rgba(84786daa)"

red = "#9d4f3f"
yellow = "#8b6909"
orange = "#995b21"
green = "#5d7636"
cyan = "#117b7c"
blue = "#2c6993"
magenta = "#905079"
brown = "#774826"

bright_red = "#8b3c2c"
bright_yellow = "#755701"
bright_green = "#4b6320"
bright_cyan = "#0f6667"
bright_blue = "#145882"
bright_magenta = "#7e3e68"
