mode = "light"

accent = "#876938"
selection = "#e0d3c1"
muted = "#84786a"

background = "#f9f1e7"
dark_background = "#f0e7db"
darker_background = "#e4dacd"
lighter_background = "#e9ded1"

foreground = "#362c1e"
dark_foreground = "#6c6154"
light_foreground = "#564b3e"
bright_foreground = "#1d140a"

hyprland_active_border = "rgba(876938ee) rgba(ac505fee) 45deg"
hyprland_inactive_border = "rgba(84786aaa)"

red = "#a24850"
yellow = "#91650e"
orange = "#a0542b"
green = "#5c7635"
cyan = "#0b7b7b"
blue = "#2c6994"
magenta = "#924f75"
brown = "#774826"

bright_red = "#90353e"
bright_yellow = "#7a5405"
bright_green = "#4a631f"
bright_cyan = "#096666"
bright_blue = "#145884"
bright_magenta = "#803d64"
