mode = "light"

accent = "#ab5902"
selection = "#edceb4"
muted = "#8d7669"

background = "#ffefe6"
dark_background = "#fbe3d6"
darker_background = "#efd6c8"
lighter_background = "#f5dacb"

foreground = "#3e281b"
dark_foreground = "#725f54"
light_foreground = "#5d483c"
bright_foreground = "#211209"

hyprland_active_border = "rgba(ab5902ee) rgba(b14c54ee) 45deg"
hyprland_inactive_border = "rgba(8d7669aa)"

red = "#982431"
yellow = "#906709"
orange = "#9b4702"
green = "#4e7646"
cyan = "#8d655e"
blue = "#9b4f03"
magenta = "#993e67"
brown = "#774826"

bright_red = "#86011f"
bright_yellow = "#775409"
bright_green = "#3c6533"
bright_cyan = "#79514a"
bright_blue = "#834102"
bright_magenta = "#872a56"
