mode = "light"

accent = "#bd4600"
selection = "#f0cbb3"
muted = "#8c7767"

background = "#fef0e5"
dark_background = "#f9e4d4"
darker_background = "#edd7c6"
lighter_background = "#f3dbc9"

foreground = "#3d2919"
dark_foreground = "#706052"
light_foreground = "#5c493a"
bright_foreground = "#201307"

hyprland_active_border = "rgba(bd4600ee) rgba(597d51ee) 45deg"
hyprland_inactive_border = "rgba(8c7767aa)"

red = "#9a2501"
yellow = "#906709"
orange = "#934e02"
green = "#4a7840"
cyan = "#377062"
blue = "#9c4702"
magenta = "#9b424d"
brown = "#774826"

bright_red = "#7f1b00"
bright_yellow = "#7a5500"
bright_green = "#37652c"
bright_cyan = "#225f51"
bright_blue = "#833a00"
bright_magenta = "#892f3c"
