mode = "dark"

accent = "#fd8d78"
selection = "#5a2d25"
muted = "#8b6862"

background = "#1b0805"
dark_background = "#140604"
darker_background = "#0e0403"
lighter_background = "#2d1512"

foreground = "#f4dbd6"
dark_foreground = "#a28b87"
light_foreground = "#dec4bf"
bright_foreground = "#fdf4f3"

hyprland_active_border = "rgba(fd8d78ee) rgba(81b482ee) 45deg"
hyprland_inactive_border = "rgba(8b6862aa)"

red = "#e36558"
yellow = "#f5cb70"
orange = "#f39850"
green = "#95c78a"
cyan = "#f4d9bb"
blue = "#df8d6d"
magenta = "#e58da1"
brown = "#865634"

bright_red = "#ef8578"
bright_yellow = "#ffe5b0"
bright_green = "#b1dba8"
bright_cyan = "#ffebd5"
bright_blue = "#eda88d"
bright_magenta = "#f4a9b9"
