mode = "dark"

accent = "#dba475"
selection = "#4a3424"
muted = "#816d62"

background = "#120904"
dark_background = "#0e0703"
darker_background = "#090502"
lighter_background = "#221610"

foreground = "#edded5"
dark_foreground = "#9a8d86"
light_foreground = "#d7c7be"
bright_foreground = "#fdf5f1"

hyprland_active_border = "rgba(dba475ee) rgba(b6a643ee) 45deg"
hyprland_inactive_border = "rgba(816d62aa)"

red = "#e4877c"
yellow = "#f9b971"
orange = "#f29e73"
green = "#afba5c"
cyan = "#61ccc7"
blue = "#6eb3e3"
magenta = "#dc8fb9"
brown = "#865634"

bright_red = "#f1a399"
bright_yellow = "#fed6ad"
bright_green = "#c5cf84"
bright_cyan = "#8ddfdc"
bright_blue = "#91c8f0"
bright_magenta = "#ebaacd"
