mode = "dark"

accent = "#fd8c7b"
selection = "#562c25"
muted = "#876a63"

background = "#150704"
dark_background = "#100503"
darker_background = "#0b0402"
lighter_background = "#261410"

foreground = "#f2dcd7"
dark_foreground = "#9e8b87"
light_foreground = "#dcc5c0"
bright_foreground = "#fdf4f3"

hyprland_active_border = "rgba(fd8c7bee) rgba(7bb76eee) 45deg"
hyprland_inactive_border = "rgba(876a63aa)"

red = "#e65849"
yellow = "#f6d476"
orange = "#f69842"
green = "#80cd82"
cyan = "#a3e0ca"
blue = "#eb9070"
magenta = "#ed90b5"
brown = "#865634"

bright_red = "#f47e6f"
bright_yellow = "#ffedbe"
bright_green = "#a1e0a2"
bright_cyan = "#c2f5e2"
bright_blue = "#f9ac91"
bright_magenta = "#fbadcb"
