mode = "light"

accent = "#bd4510"
selection = "#dfd0bb"
muted = "#6e8071"

background = "#e9f7eb"
dark_background = "#ddeee0"
darker_background = "#cfe1d2"
lighter_background = "#d3e6d6"

foreground = "#213325"
dark_foreground = "#57685a"
light_foreground = "#415244"
bright_foreground = "#0c1a0f"

hyprland_active_border = "rgba(bd4510ee) rgba(3b834eee) 45deg"
hyprland_inactive_border = "rgba(6e8071aa)"

red = "#b3372d"
yellow = "#8f6908"
orange = "#a45400"
green = "#1c7f30"
cyan = "#0b7b7d"
blue = "#0769a0"
magenta = "#a13e80"
brown = "#774826"

bright_red = "#a11d17"
bright_yellow = "#775605"
bright_green = "#076a22"
bright_cyan = "#036668"
bright_blue = "#065786"
bright_magenta = "#8f286f"
