mode = "light"

accent = "#a35475"
selection = "#e8cecf"
muted = "#87776c"

background = "#fbf0e9"
dark_background = "#f3e6dd"
darker_background = "#e6d8cf"
lighter_background = "#ecddd3"

foreground = "#392a21"
dark_foreground = "#6f6056"
light_foreground = "#584a40"
bright_foreground = "#1e130c"

hyprland_active_border = "rgba(a35475ee) rgba(99633dee) 45deg"
hyprland_inactive_border = "rgba(87776caa)"

red = "#94343a"
yellow = "#936412"
orange = "#994b1e"
green = "#5a6e46"
cyan = "#8a6754"
blue = "#7b4d77"
magenta = "#823156"
brown = "#774826"

bright_red = "#821e29"
bright_yellow = "#7c5308"
bright_green = "#495d34"
bright_cyan = "#76533f"
bright_blue = "#6a3c66"
bright_magenta = "#711d45"
