mode = "dark"

accent = "#cdad63"
selection = "#44381e"
muted = "#7a715d"

background = "#0f0a03"
dark_background = "#0b0802"
darker_background = "#080502"
lighter_background = "#1e190d"

foreground = "#e7e1d2"
dark_foreground = "#958f83"
light_foreground = "#d1caba"
bright_foreground = "#faf6ef"

hyprland_active_border = "rgba(cdad63ee) rgba(8cb180ee) 45deg"
hyprland_inactive_border = "rgba(7a715daa)"

red = "#e4877c"
yellow = "#ecc06a"
orange = "#efa16b"
green = "#93c07e"
cyan = "#5dcbcd"
blue = "#72b2e6"
magenta = "#da8fbd"
brown = "#865634"

bright_red = "#f1a399"
bright_yellow = "#fdd994"
bright_green = "#afd49d"
bright_cyan = "#8adfdf"
bright_blue = "#94c7f3"
bright_magenta = "#eaaad0"
