mode = "light"

accent = "#806c03"
selection = "#ded5b1"
muted = "#817a65"

background = "#f8f2e2"
dark_background = "#efe8d5"
darker_background = "#e2dbc6"
lighter_background = "#e8e0c9"

foreground = "#342d18"
dark_foreground = "#696350"
light_foreground = "#534d39"
bright_foreground = "#1b1606"

hyprland_active_border = "rgba(806c03ee) rgba(a7593dee) 45deg"
hyprland_inactive_border = "rgba(817a65aa)"

red = "#ac4135"
yellow = "#876b00"
orange = "#9e5808"
green = "#4d7b24"
cyan = "#0a7b7c"
blue = "#096a9d"
magenta = "#9b457d"
brown = "#774826"

bright_red = "#9a2b21"
bright_yellow = "#715901"
bright_green = "#396700"
bright_cyan = "#056667"
bright_blue = "#005886"
bright_magenta = "#89316c"
