mode = "dark"

accent = "#9ebf68"
selection = "#334121"
muted = "#6a7661"

background = "#091005"
dark_background = "#070c04"
darker_background = "#050803"
lighter_background = "#171f11"

foreground = "#dce5d5"
dark_foreground = "#8c9486"
light_foreground = "#c4cebd"
bright_foreground = "#f4f8f1"

hyprland_active_border = "rgba(9ebf68ee) rgba(b6a369ee) 45deg"
hyprland_inactive_border = "rgba(6a7661aa)"

red = "#df8071"
yellow = "#e4dc71"
orange = "#efaa5c"
green = "#9cc86c"
cyan = "#b1dfb9"
blue = "#c2a678"
magenta = "#df9da1"
brown = "#865634"

bright_red = "#ec9c8f"
bright_yellow = "#f8f39d"
bright_green = "#b7dc91"
bright_cyan = "#cef4d4"
bright_blue = "#d4bd97"
bright_magenta = "#efb7ba"
