mode = "dark"

accent = "#f49851"
selection = "#522d1a"
muted = "#896868"

background = "#130304"
dark_background = "#0e0203"
darker_background = "#0a0202"
lighter_background = "#240f10"

foreground = "#f4dada"
dark_foreground = "#9f8889"
light_foreground = "#dec3c3"
bright_foreground = "#fef4f4"

hyprland_active_border = "rgba(f49851ee) rgba(e68488ee) 45deg"
hyprland_inactive_border = "rgba(896868aa)"

red = "#da6b6e"
yellow = "#fac871"
orange = "#f29762"
green = "#9dc494"
cyan = "#fed2cb"
blue = "#f0995b"
magenta = "#e68aaf"
brown = "#865634"

bright_red = "#e78989"
bright_yellow = "#fee4b8"
bright_green = "#b7d9b0"
bright_cyan = "#fceae6"
bright_blue = "#fdb583"
bright_magenta = "#f4a7c4"
