mode = "light"

accent = "#777046"
selection = "#d9d6c6"
muted = "#7e7a6d"

background = "#f5f3ea"
dark_background = "#ebe9de"
darker_background = "#dedbd0"
lighter_background = "#e4e0d4"

foreground = "#312e22"
dark_foreground = "#676355"
light_foreground = "#504d41"
bright_foreground = "#19160c"

hyprland_active_border = "rgba(777046ee) rgba(587e41ee) 45deg"
hyprland_inactive_border = "rgba(7e7a6daa)"

red = "#96534c"
yellow = "#896929"
orange = "#945c36"
green = "#56773a"
cyan = "#217a78"
blue = "#38688f"
magenta = "#8b5477"
brown = "#774826"

bright_red = "#84413b"
bright_yellow = "#76560a"
bright_green = "#436524"
bright_cyan = "#016765"
bright_blue = "#25577e"
bright_magenta = "#794366"
