mode = "dark"

accent = "#fd8c7b"
selection = "#4a2e27"
muted = "#66766e"

background = "#040906"
dark_background = "#030705"
darker_background = "#020503"
lighter_background = "#0f1713"

foreground = "#d9e5df"
dark_foreground = "#88918d"
light_foreground = "#c1cec8"
bright_foreground = "#f1f9f5"

hyprland_active_border = "rgba(fd8c7bee) rgba(e28e3aee) 45deg"
hyprland_inactive_border = "rgba(66766eaa)"

red = "#f9786b"
yellow = "#feb857"
orange = "#fe985b"
green = "#90c365"
cyan = "#04d1d4"
blue = "#5ab3f8"
magenta = "#e785c1"
brown = "#865634"

bright_red = "#ff9c90"
bright_yellow = "#fed7a6"
bright_green = "#acd78b"
bright_cyan = "#6be4e6"
bright_blue = "#8ac8fd"
bright_magenta = "#f5a3d4"
