mode = "dark"

accent = "#c4b164"
selection = "#423c1f"
muted = "#75735e"

background = "#0f0e04"
dark_background = "#0b0b03"
darker_background = "#080702"
lighter_background = "#1e1c10"

foreground = "#e4e2d3"
dark_foreground = "#939184"
light_foreground = "#cdcbbb"
bright_foreground = "#f8f7f0"

hyprland_active_border = "rgba(c4b164ee) rgba(c293bdee) 45deg"
hyprland_inactive_border = "rgba(75735eaa)"

red = "#e4877f"
yellow = "#e0c66a"
orange = "#eca367"
green = "#98bf79"
cyan = "#5bccca"
blue = "#6eb3e6"
magenta = "#d391ca"
brown = "#865634"

bright_red = "#f2a39c"
bright_yellow = "#f2de94"
bright_green = "#b2d39a"
bright_cyan = "#89dfde"
bright_blue = "#91c8f3"
bright_magenta = "#e3acdc"
