mode = "dark"

accent = "#92b0f1"
selection = "#2d3751"
muted = "#6a7186"

background = "#060813"
dark_background = "#05060e"
darker_background = "#03040a"
lighter_background = "#131623"

foreground = "#dce1f1"
dark_foreground = "#8b8f9d"
light_foreground = "#c5cadb"
bright_foreground = "#f4f7fe"

hyprland_active_border = "rgba(92b0f1ee) rgba(80b38aee) 45deg"
hyprland_inactive_border = "rgba(6a7186aa)"

red = "#e68485"
yellow = "#f0d49b"
orange = "#f1ac81"
green = "#88ca95"
cyan = "#8ed7ef"
blue = "#83a3ea"
magenta = "#bea3df"
brown = "#865634"

bright_red = "#f3a1a0"
bright_yellow = "#feedc9"
bright_green = "#a8deb2"
bright_cyan = "#b5ebfd"
bright_blue = "#9ebaf5"
bright_magenta = "#d2bcee"
