mode = "light"

accent = "#826b41"
selection = "#e0d3c5"
muted = "#86776d"

background = "#faf0ea"
dark_background = "#f2e6de"
darker_background = "#e5d9d0"
lighter_background = "#ebddd4"

foreground = "#382b21"
dark_foreground = "#6e6056"
light_foreground = "#584a40"
bright_foreground = "#1e140c"

hyprland_active_border = "rgba(826b41ee) rgba(a8545dee) 45deg"
hyprland_inactive_border = "rgba(86776daa)"

red = "#9e4c50"
yellow = "#8a6908"
orange = "#9c5829"
green = "#59773a"
cyan = "#117b7c"
blue = "#2b6993"
magenta = "#88476c"
brown = "#774826"

bright_red = "#8c3a3e"
bright_yellow = "#745700"
bright_green = "#466424"
bright_cyan = "#0f6667"
bright_blue = "#125882"
bright_magenta = "#76355c"
