mode = "light"

accent = "#b5475b"
selection = "#eccbca"
muted = "#8c7568"

background = "#fcf0e9"
dark_background = "#fbe3d7"
darker_background = "#efd5c8"
lighter_background = "#f6dacc"

foreground = "#3e281c"
dark_foreground = "#725e55"
light_foreground = "#5d483c"
bright_foreground = "#21120a"

hyprland_active_border = "rgba(b5475bee) rgba(926833ee) 45deg"
hyprland_inactive_border = "rgba(8c7568aa)"

red = "#ac3f46"
yellow = "#966508"
orange = "#a6511f"
green = "#517a1b"
cyan = "#0d7b7c"
blue = "#0769a0"
magenta = "#9c447c"
brown = "#774826"

bright_red = "#9a2934"
bright_yellow = "#7c5306"
bright_green = "#406603"
bright_cyan = "#076667"
bright_blue = "#075786"
bright_magenta = "#8a306b"
