mode = "dark"

accent = "#fd8c7e"
selection = "#4a3128"
muted = "#647767"

background = "#040e06"
dark_background = "#030b05"
darker_background = "#020703"
lighter_background = "#101d13"

foreground = "#d7e6da"
dark_foreground = "#879489"
light_foreground = "#c0cfc2"
bright_foreground = "#f2f9f3"

hyprland_active_border = "rgba(fd8c7eee) rgba(6dba70ee) 45deg"
hyprland_inactive_border = "rgba(647767aa)"

red = "#e8594d"
yellow = "#f2d76c"
orange = "#f89938"
green = "#6fd087"
cyan = "#93e3d8"
blue = "#7bb2d9"
magenta = "#e492c9"
brown = "#865634"

bright_red = "#f57e71"
bright_yellow = "#feefb4"
bright_green = "#95e3a6"
bright_cyan = "#b7f7ee"
bright_blue = "#9bc7e7"
bright_magenta = "#f3aedb"
