mode = "dark"

accent = "#d8a57e"
selection = "#433327"
muted = "#797068"

background = "#090705"
dark_background = "#070504"
darker_background = "#050403"
lighter_background = "#171412"

foreground = "#e7e0d9"
dark_foreground = "#938e88"
light_foreground = "#d1c9c1"
bright_foreground = "#fcf6f0"

hyprland_active_border = "rgba(d8a57eee) rgba(80b38aee) 45deg"
hyprland_inactive_border = "rgba(797068aa)"

red = "#df8071"
yellow = "#f4ca84"
orange = "#eea471"
green = "#98c598"
cyan = "#d5d2bc"
blue = "#c3a48c"
magenta = "#e3a8b0"
brown = "#865634"

bright_red = "#ec9c8f"
bright_yellow = "#fee4ba"
bright_green = "#b4d9b4"
bright_cyan = "#ebe9d6"
bright_blue = "#d6bba7"
bright_magenta = "#f3c2c8"
