mode = "dark"

accent = "#fd8c7b"
selection = "#493033"
muted = "#617488"

background = "#030c17"
dark_background = "#020911"
darker_background = "#02060c"
lighter_background = "#0e1a28"

foreground = "#d5e3f2"
dark_foreground = "#85919f"
light_foreground = "#beccdc"
bright_foreground = "#f2f7fd"

hyprland_active_border = "rgba(fd8c7bee) rgba(8ab181ee) 45deg"
hyprland_inactive_border = "rgba(617488aa)"

red = "#e76250"
yellow = "#f4d580"
orange = "#f59d4f"
green = "#95c78a"
cyan = "#9be0db"
blue = "#84afdc"
magenta = "#ea93ae"
brown = "#865634"

bright_red = "#f28372"
bright_yellow = "#feeec1"
bright_green = "#b1dba8"
bright_cyan = "#bcf5f0"
bright_blue = "#a1c5ea"
bright_magenta = "#f9afc5"
