mode = "light"

accent = "#7c6e40"
selection = "#dad5c5"
muted = "#7f7a6d"

background = "#f5f2ea"
dark_background = "#ece8de"
darker_background = "#dfdbd0"
lighter_background = "#e4e0d4"

foreground = "#322d22"
dark_foreground = "#686355"
light_foreground = "#514d41"
bright_foreground = "#19160c"

hyprland_active_border = "rgba(7c6e40ee) rgba(4a814cee) 45deg"
hyprland_inactive_border = "rgba(7f7a6daa)"

red = "#9e4d4b"
yellow = "#8b6909"
orange = "#9b5927"
green = "#4f7940"
cyan = "#017b7e"
blue = "#2b6895"
magenta = "#90507a"
brown = "#774826"

bright_red = "#8c3a3a"
bright_yellow = "#755701"
bright_green = "#3b662b"
bright_cyan = "#026668"
bright_blue = "#125784"
bright_magenta = "#7e3e6a"
