mode = "dark"

accent = "#eae0a2"
selection = "#4a4f3c"
muted = "#627772"

background = "#0c1614"
dark_background = "#09110f"
darker_background = "#060b0a"
lighter_background = "#1a2623"

foreground = "#d6e5e2"
dark_foreground = "#899694"
light_foreground = "#becfcb"
bright_foreground = "#f0f9f7"

hyprland_active_border = "rgba(eae0a2ee) rgba(6ab5a5ee) 45deg"
hyprland_inactive_border = "rgba(627772aa)"

red = "#e18881"
yellow = "#f0de99"
orange = "#f1b17e"
green = "#94cf9f"
cyan = "#93e3d8"
blue = "#74bdd4"
magenta = "#d8aed3"
brown = "#885836"

bright_red = "#efa49d"
bright_yellow = "#feefb6"
bright_green = "#b3e3bb"
bright_cyan = "#b7f7ee"
bright_blue = "#97d2e5"
bright_magenta = "#ebc7e6"
