mode = "dark"

accent = "#caae63"
selection = "#4a3e21"
muted = "#79715b"

background = "#181307"
dark_background = "#120e05"
darker_background = "#0c0a04"
lighter_background = "#272314"

foreground = "#e6e1d1"
dark_foreground = "#989384"
light_foreground = "#d0cab9"
bright_foreground = "#f9f7ef"

hyprland_active_border = "rgba(caae63ee) rgba(83b478ee) 45deg"
hyprland_inactive_border = "rgba(79715baa)"

red = "#e4877d"
yellow = "#e8c36a"
orange = "#eea269"
green = "#8fc181"
cyan = "#5bcccb"
blue = "#6db3e6"
magenta = "#db8fbd"
brown = "#885836"

bright_red = "#f2a39a"
bright_yellow = "#fadb94"
bright_green = "#abd59f"
bright_cyan = "#89dfde"
bright_blue = "#90c8f3"
bright_magenta = "#ebaad0"
