mode = "dark"

accent = "#fd8e67"
selection = "#582b1e"
muted = "#8a685e"

background = "#180502"
dark_background = "#120402"
darker_background = "#0c0301"
lighter_background = "#29120b"

foreground = "#f4dbd3"
dark_foreground = "#a08a84"
light_foreground = "#ddc4bd"
bright_foreground = "#fdf5f2"

hyprland_active_border = "rgba(fd8e67ee) rgba(ae96daee) 45deg"
hyprland_inactive_border = "rgba(8a685eaa)"

red = "#e36650"
yellow = "#ffc75a"
orange = "#f89545"
green = "#9cc685"
cyan = "#a5d5d7"
blue = "#a498e5"
magenta = "#d198e3"
brown = "#865634"

bright_red = "#ee8672"
bright_yellow = "#ffe4b5"
bright_green = "#b7daa4"
bright_cyan = "#c3eaec"
bright_blue = "#b9b1f1"
bright_magenta = "#e2b3f1"
