mode = "light"

accent = "#b25117"
selection = "#edcdb7"
muted = "#8a7665"

background = "#fdf0e4"
dark_background = "#f8e5d4"
darker_background = "#ecd7c5"
lighter_background = "#f3dcc8"

foreground = "#3c2918"
dark_foreground = "#706052"
light_foreground = "#5b4939"
bright_foreground = "#201307"

hyprland_active_border = "rgba(b25117ee) rgba(a35475ee) 45deg"
hyprland_inactive_border = "rgba(8a7665aa)"

red = "#ab4231"
yellow = "#8d680c"
orange = "#a05609"
green = "#57791b"
cyan = "#017c78"
blue = "#0a6a9c"
magenta = "#9f4471"
brown = "#774826"

bright_red = "#992c1b"
bright_yellow = "#775600"
bright_green = "#466504"
bright_cyan = "#006764"
bright_blue = "#005884"
bright_magenta = "#8d3060"
