mode = "dark"

accent = "#d7b894"
selection = "#46392d"
muted = "#7b6f65"

background = "#0d0805"
dark_background = "#0a0604"
darker_background = "#070403"
lighter_background = "#1b1612"

foreground = "#e9dfd8"
dark_foreground = "#958d88"
light_foreground = "#d3c8c0"
bright_foreground = "#fcf5f0"

hyprland_active_border = "rgba(d7b894ee) rgba(d78f83ee) 45deg"
hyprland_inactive_border = "rgba(7b6f65aa)"

red = "#dc8c83"
yellow = "#e7c27a"
orange = "#e8a577"
green = "#a0bc81"
cyan = "#71c9c5"
blue = "#7ab2dc"
magenta = "#d693b7"
brown = "#865634"

bright_red = "#eba79f"
bright_yellow = "#f9daa0"
bright_green = "#b9d19f"
bright_cyan = "#97ddd9"
bright_blue = "#9ac7eb"
bright_magenta = "#e6aecb"
