mode = "light"

accent = "#487c23"
selection = "#c6dcbc"
muted = "#6e7e6b"

background = "#eaf7e7"
dark_background = "#deeedb"
darker_background = "#d0e1cd"
lighter_background = "#d4e7d0"

foreground = "#233320"
dark_foreground = "#5a6857"
light_foreground = "#435240"
bright_foreground = "#0f190c"

hyprland_active_border = "rgba(487c23ee) rgba(88763fee) 45deg"
hyprland_inactive_border = "rgba(6e7e6baa)"

red = "#98392d"
yellow = "#826d09"
orange = "#925406"
green = "#477a23"
cyan = "#00584c"
blue = "#2b6f4f"
magenta = "#8b567a"
brown = "#774826"

bright_red = "#862419"
bright_yellow = "#6d5b01"
bright_green = "#336700"
bright_cyan = "#01463c"
bright_blue = "#115e3e"
bright_magenta = "#7a4469"
