mode = "light"

accent = "#6a751c"
selection = "#d6d7b7"
muted = "#7e7b66"

background = "#f5f3e3"
dark_background = "#ece9d7"
darker_background = "#dfdcc8"
lighter_background = "#e4e1cb"

foreground = "#312e1a"
dark_foreground = "#676450"
light_foreground = "#504e3a"
bright_foreground = "#191607"

hyprland_active_border = "rgba(6a751cee) rgba(b04c60ee) 45deg"
hyprland_inactive_border = "rgba(7e7b66aa)"

red = "#9b3142"
yellow = "#786405"
orange = "#934a00"
green = "#5e7729"
cyan = "#7c6d52"
blue = "#486e50"
magenta = "#935172"
brown = "#774826"

bright_red = "#891931"
bright_yellow = "#655300"
bright_green = "#4a6309"
bright_cyan = "#69593e"
bright_blue = "#365d3f"
bright_magenta = "#823f61"
