mode = "dark"

accent = "#ccae4e"
selection = "#453719"
muted = "#7f6e61"

background = "#110904"
dark_background = "#0d0703"
darker_background = "#090502"
lighter_background = "#21170f"

foreground = "#ecdfd5"
dark_foreground = "#998e86"
light_foreground = "#d6c8bd"
bright_foreground = "#fcf5f0"

hyprland_active_border = "rgba(ccae4eee) rgba(cf957bee) 45deg"
hyprland_inactive_border = "rgba(7f6e61aa)"

red = "#e48879"
yellow = "#e6c465"
orange = "#eda365"
green = "#9abf7a"
cyan = "#61ccc7"
blue = "#71b2e4"
magenta = "#dc8fb9"
brown = "#865634"

bright_red = "#f2a497"
bright_yellow = "#f8dc91"
bright_green = "#b5d39a"
bright_cyan = "#8ddfdb"
bright_blue = "#93c7f1"
bright_magenta = "#ecaacd"
