mode = "light"

accent = "#896a0b"
selection = "#dfd4b4"
muted = "#807a67"

background = "#f7f2e4"
dark_background = "#eee8d7"
darker_background = "#e1dbc9"
lighter_background = "#e6e0cc"

foreground = "#332d1b"
dark_foreground = "#696350"
light_foreground = "#534d3b"
bright_foreground = "#1a1607"

hyprland_active_border = "rgba(896a0bee) rgba(a7593dee) 45deg"
hyprland_inactive_border = "rgba(807a67aa)"

red = "#ab422e"
yellow = "#876b09"
orange = "#9c5907"
green = "#55791b"
cyan = "#0a7a77"
blue = "#0069a4"
magenta = "#9c457a"
brown = "#774826"

bright_red = "#992c18"
bright_yellow = "#6f5808"
bright_green = "#446503"
bright_cyan = "#056562"
bright_blue = "#02578a"
bright_magenta = "#8b3169"
