mode = "light"

accent = "#846d00"
selection = "#e1d4b3"
muted = "#867868"

background = "#fbf1e5"
dark_background = "#f3e6d8"
darker_background = "#e6d9ca"
lighter_background = "#ecdecd"

foreground = "#382b1b"
dark_foreground = "#6e6151"
light_foreground = "#574b3b"
bright_foreground = "#1e1408"

hyprland_active_border = "rgba(846d00ee) rgba(518047ee) 45deg"
hyprland_inactive_border = "rgba(867868aa)"

red = "#a54746"
yellow = "#886b00"
orange = "#9e5719"
green = "#497b38"
cyan = "#0b7b7b"
blue = "#1d699c"
magenta = "#954b7c"
brown = "#774826"

bright_red = "#933334"
bright_yellow = "#705803"
bright_green = "#346721"
bright_cyan = "#076666"
bright_blue = "#015789"
bright_magenta = "#84386b"
