mode = "light"

accent = "#97623b"
selection = "#e5d1c3"
muted = "#87776c"

background = "#fbf0e9"
dark_background = "#f3e6dd"
darker_background = "#e6d8cf"
lighter_background = "#ecddd3"

foreground = "#392a21"
dark_foreground = "#6f6056"
light_foreground = "#584a40"
bright_foreground = "#1e130c"

hyprland_active_border = "rgba(97623bee) rgba(757635ee) 45deg"
hyprland_inactive_border = "rgba(87776caa)"

red = "#9d4f3f"
yellow = "#775902"
orange = "#8e531d"
green = "#69742f"
cyan = "#117b7b"
blue = "#2e6893"
magenta = "#8f5079"
brown = "#774826"

bright_red = "#8c3c2d"
bright_yellow = "#634900"
bright_green = "#556013"
bright_cyan = "#0f6666"
bright_blue = "#155782"
bright_magenta = "#7e3e68"
