mode = "light"

accent = "#8e673c"
selection = "#d7d5cf"
muted = "#6e7d84"

background = "#ebf4f9"
dark_background = "#dfebf0"
darker_background = "#d2dee4"
lighter_background = "#d6e3e9"

foreground = "#223037"
dark_foreground = "#57666e"
light_foreground = "#424f56"
bright_foreground = "#0d181d"

hyprland_active_border = "rgba(8e673cee) rgba(ad5248ee) 45deg"
hyprland_inactive_border = "rgba(6e7d84aa)"

red = "#a24a3f"
yellow = "#946614"
orange = "#9f5725"
green = "#56783a"
cyan = "#017b7d"
blue = "#2b6895"
magenta = "#8f507b"
brown = "#774826"

bright_red = "#90372c"
bright_yellow = "#7c5308"
bright_green = "#436525"
bright_cyan = "#026668"
bright_blue = "#125784"
bright_magenta = "#7e3e6a"
