mode = "light"

accent = "#5f7828"
selection = "#d3d9bc"
muted = "#7c7c69"

background = "#f4f4e6"
dark_background = "#eaead9"
darker_background = "#ddddcb"
lighter_background = "#e2e2cf"

foreground = "#302f1d"
dark_foreground = "#656552"
light_foreground = "#4f4e3d"
bright_foreground = "#171709"

hyprland_active_border = "rgba(5f7828ee) rgba(8e693dee) 45deg"
hyprland_inactive_border = "rgba(7c7c69aa)"

red = "#9e4d4b"
yellow = "#966417"
orange = "#9e5730"
green = "#5d782c"
cyan = "#137b79"
blue = "#296996"
magenta = "#924f77"
brown = "#774826"

bright_red = "#8c3a3a"
bright_yellow = "#805202"
bright_green = "#49640e"
bright_cyan = "#006765"
bright_blue = "#0e5885"
bright_magenta = "#803d66"
