mode = "dark"

accent = "#dfa635"
selection = "#503a11"
muted = "#7d7058"

background = "#181003"
dark_background = "#120c02"
darker_background = "#0c0802"
lighter_background = "#281f0e"

foreground = "#eae0cf"
dark_foreground = "#9a9181"
light_foreground = "#d4c9b7"
bright_foreground = "#faf6ef"

hyprland_active_border = "rgba(dfa635ee) rgba(92b07bee) 45deg"
hyprland_inactive_border = "rgba(7d7058aa)"

red = "#ec8274"
yellow = "#f7bc50"
orange = "#f89c5c"
green = "#9abf6e"
cyan = "#4ccecc"
blue = "#61b4ea"
magenta = "#e28abc"
brown = "#865634"

bright_red = "#f8a093"
bright_yellow = "#fed899"
bright_green = "#b4d391"
bright_cyan = "#80e1df"
bright_blue = "#87c9f6"
bright_magenta = "#f0a7cf"
