mode = "dark"

accent = "#d5cc97"
selection = "#444533"
muted = "#69766b"

background = "#0b110c"
dark_background = "#080d09"
darker_background = "#060906"
lighter_background = "#19201b"

foreground = "#dae4dc"
dark_foreground = "#8b948d"
light_foreground = "#c3cec5"
bright_foreground = "#f2f9f3"

hyprland_active_border = "rgba(d5cc97ee) rgba(bb95c4ee) 45deg"
hyprland_inactive_border = "rgba(69766baa)"

red = "#dc8c83"
yellow = "#dac87a"
orange = "#e4a772"
green = "#9abe81"
cyan = "#6acaca"
blue = "#76b2e0"
magenta = "#ce95c7"
brown = "#865634"

bright_red = "#eba79e"
bright_yellow = "#eedfa0"
bright_green = "#b4d2a0"
bright_cyan = "#92dede"
bright_blue = "#97c7ee"
bright_magenta = "#dfafd9"
