mode = "dark"

accent = "#b8b756"
selection = "#3d3d1a"
muted = "#72745d"

background = "#0d0e03"
dark_background = "#0a0b02"
darker_background = "#070702"
lighter_background = "#1c1d0e"

foreground = "#e1e3d2"
dark_foreground = "#909283"
light_foreground = "#caccbb"
bright_foreground = "#f7f8f0"

hyprland_active_border = "rgba(b8b756ee) rgba(ca9971ee) 45deg"
hyprland_inactive_border = "rgba(72745daa)"

red = "#de826a"
yellow = "#f4e06a"
orange = "#f5ad5b"
green = "#abcc6b"
cyan = "#ace0b6"
blue = "#cca273"
magenta = "#df9da1"
brown = "#865634"

bright_red = "#ec9e8a"
bright_yellow = "#fff19d"
bright_green = "#c4e193"
bright_cyan = "#c9f5d1"
bright_blue = "#ddba93"
bright_magenta = "#efb7ba"
