mode = "dark"

accent = "#dda552"
selection = "#4e381a"
muted = "#7f6e5c"

background = "#160d04"
dark_background = "#110a03"
darker_background = "#0b0702"
lighter_background = "#261c10"

foreground = "#ebdfd2"
dark_foreground = "#9a8f84"
light_foreground = "#d5c8ba"
bright_foreground = "#fbf6f0"

hyprland_active_border = "rgba(dda552ee) rgba(d9906fee) 45deg"
hyprland_inactive_border = "rgba(7f6e5caa)"

red = "#e48875"
yellow = "#f5bc69"
orange = "#f1a06b"
green = "#a0bd77"
cyan = "#64cbc4"
blue = "#6cb4e1"
magenta = "#d990be"
brown = "#865634"

bright_red = "#f1a494"
bright_yellow = "#fdd7a4"
bright_green = "#b9d298"
bright_cyan = "#8edfd8"
bright_blue = "#90c9ee"
bright_magenta = "#e9abd1"
