mode = "light"

accent = "#896944"
selection = "#e0d3c5"
muted = "#82796e"

background = "#f8f1ea"
dark_background = "#efe7de"
darker_background = "#e2dad0"
lighter_background = "#e7dfd4"

foreground = "#352c22"
dark_foreground = "#6b6156"
light_foreground = "#544c41"
bright_foreground = "#1b150d"

hyprland_active_border = "rgba(896944ee) rgba(a35a4eee) 45deg"
hyprland_inactive_border = "rgba(82796eaa)"

red = "#9e4e47"
yellow = "#8d680a"
orange = "#9b5927"
green = "#5b7638"
cyan = "#137b79"
blue = "#2c6993"
magenta = "#925074"
brown = "#774826"

bright_red = "#8c3b35"
bright_yellow = "#775602"
bright_green = "#486422"
bright_cyan = "#0d6562"
bright_blue = "#145882"
bright_magenta = "#803e64"
