mode = "light"

accent = "#6c7428"
selection = "#d6d7bb"
muted = "#7d7b68"

background = "#f4f3e5"
dark_background = "#ebe9d9"
darker_background = "#dedccb"
lighter_background = "#e3e1ce"

foreground = "#312f1c"
dark_foreground = "#666452"
light_foreground = "#504e3c"
bright_foreground = "#181708"

hyprland_active_border = "rgba(6c7428ee) rgba(8a6b45ee) 45deg"
hyprland_inactive_border = "rgba(7d7b68aa)"

red = "#9e4d4a"
yellow = "#8c6809"
orange = "#9b5827"
green = "#68752c"
cyan = "#127b7b"
blue = "#2e6897"
magenta = "#924f76"
brown = "#774826"

bright_red = "#8c3a39"
bright_yellow = "#755701"
bright_green = "#55610e"
bright_cyan = "#0f6666"
bright_blue = "#175786"
bright_magenta = "#803d66"
