mode = "light"

accent = "#7562a9"
selection = "#d7d1ea"
muted = "#7c7788"

background = "#f3f0fc"
dark_background = "#eae6f4"
darker_background = "#ddd9e7"
lighter_background = "#e2deed"

foreground = "#2f2b3a"
dark_foreground = "#656070"
light_foreground = "#4e4a59"
bright_foreground = "#17141f"

hyprland_active_border = "rgba(7562a9ee) rgba(857450ee) 45deg"
hyprland_inactive_border = "rgba(7c7788aa)"

red = "#953e57"
yellow = "#826a2c"
orange = "#96522f"
green = "#4e764f"
cyan = "#49728f"
blue = "#63579c"
magenta = "#643b81"
brown = "#774826"

bright_red = "#832b46"
bright_yellow = "#705710"
bright_green = "#3a643c"
bright_cyan = "#355f7c"
bright_blue = "#53458b"
bright_magenta = "#542870"
