mode = "dark"

accent = "#afb875"
selection = "#3b4026"
muted = "#6f7460"

background = "#0e1107"
dark_background = "#0b0d05"
darker_background = "#070904"
lighter_background = "#1d2013"

foreground = "#dfe4d5"
dark_foreground = "#909487"
light_foreground = "#c8cdbd"
bright_foreground = "#f6f8f0"

hyprland_active_border = "rgba(afb875ee) rgba(bc9f7bee) 45deg"
hyprland_inactive_border = "rgba(6f7460aa)"

red = "#dc8b86"
yellow = "#e6c27a"
orange = "#e8a478"
green = "#abb976"
cyan = "#6ccac8"
blue = "#7bb1e0"
magenta = "#d693b9"
brown = "#865634"

bright_red = "#eaa6a1"
bright_yellow = "#f7da9f"
bright_green = "#c2ce97"
bright_cyan = "#94dedc"
bright_blue = "#9ac6ee"
bright_magenta = "#e6adcd"
