mode = "dark"

accent = "#d2a96f"
selection = "#4b3922"
muted = "#7e6f5c"

background = "#160e04"
dark_background = "#110b03"
darker_background = "#0b0702"
lighter_background = "#261c10"

foreground = "#ebdfd2"
dark_foreground = "#9a9084"
light_foreground = "#d5c8ba"
bright_foreground = "#fbf6f0"

hyprland_active_border = "rgba(d2a96fee) rgba(8cb088ee) 45deg"
hyprland_inactive_border = "rgba(7e6f5caa)"

red = "#e48682"
yellow = "#f2bd6c"
orange = "#f19f71"
green = "#93c07f"
cyan = "#60cbca"
blue = "#6eb3e3"
magenta = "#db8fbb"
brown = "#865634"

bright_red = "#f1a29e"
bright_yellow = "#fed79e"
bright_green = "#afd49e"
bright_cyan = "#8cdfdd"
bright_blue = "#90c8f0"
bright_magenta = "#eaaacf"
