mode = "light"

accent = "#806c40"
selection = "#ded4c4"
muted = "#83796c"

background = "#f8f1e9"
dark_background = "#efe7de"
darker_background = "#e2dad0"
lighter_background = "#e8dfd4"

foreground = "#352c20"
dark_foreground = "#6b6255"
light_foreground = "#554b40"
bright_foreground = "#1c150b"

hyprland_active_border = "rgba(806c40ee) rgba(9f5f39ee) 45deg"
hyprland_inactive_border = "rgba(83796caa)"

red = "#943e32"
yellow = "#896a09"
orange = "#945311"
green = "#607240"
cyan = "#5c5539"
blue = "#80593f"
magenta = "#95545f"
brown = "#774826"

bright_red = "#822a20"
bright_yellow = "#735800"
bright_green = "#4f612d"
bright_cyan = "#4c4528"
bright_blue = "#6f482d"
bright_magenta = "#83424e"
