mode = "dark"

accent = "#f8907c"
selection = "#523025"
muted = "#7d6f5d"

background = "#110a03"
dark_background = "#0d0802"
darker_background = "#090502"
lighter_background = "#20180c"

foreground = "#eae0d2"
dark_foreground = "#988f83"
light_foreground = "#d4c9ba"
bright_foreground = "#fbf6f0"

hyprland_active_border = "rgba(f8907cee) rgba(bca341ee) 45deg"
hyprland_inactive_border = "rgba(7d6f5daa)"

red = "#ec8276"
yellow = "#e9c358"
orange = "#f4a05a"
green = "#96c171"
cyan = "#48cecc"
blue = "#65b3ed"
magenta = "#e18abd"
brown = "#865634"

bright_red = "#f99f94"
bright_yellow = "#fbdb88"
bright_green = "#b1d594"
bright_cyan = "#7ee1df"
bright_blue = "#8ac9f9"
bright_magenta = "#f0a6d0"
