mode = "light"

accent = "#ba434e"
selection = "#eccbc4"
muted = "#857868"

background = "#faf1e5"
dark_background = "#f2e7d9"
darker_background = "#e5d9cb"
lighter_background = "#ebdece"

foreground = "#372c1c"
dark_foreground = "#6d6152"
light_foreground = "#574b3c"
bright_foreground = "#1d1408"

hyprland_active_border = "rgba(ba434eee) rgba(896d2eee) 45deg"
hyprland_inactive_border = "rgba(857868aa)"

red = "#9c1c29"
yellow = "#8c6905"
orange = "#974a00"
green = "#5f7339"
cyan = "#796243"
blue = "#8e4a38"
magenta = "#81354a"
brown = "#774826"

bright_red = "#86001a"
bright_yellow = "#735606"
bright_green = "#4e6225"
bright_cyan = "#685131"
bright_blue = "#7d3827"
bright_magenta = "#70223a"
